# Generated by Django 4.2.29 on 2026-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_categories/')),
                ('link', models.CharField(help_text='Masalan: /catalog/birthday', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Promo kategoriya (Kimga sovg'a)",
                'verbose_name_plural': "Promo kategoriyalar (Kimga sovg'a)",
                'ordering': ['order', 'id'],
            },
        ),
    ]
