# Generated by Django 4.2.29 on 2026-03-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_promo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_categories', to='store.category', verbose_name='Kategoriya (havola)'),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='link',
            field=models.CharField(blank=True, help_text="Agar kategoriya tanlanmasa, qo'lda kiriting. Masalan: /catalog/birthday", max_length=500),
        ),
    ]
