# Generated by Django 4.2.29 on 2026-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_promocategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_categories',
            field=models.ManyToManyField(blank=True, help_text="Mahsulot qaysi «Kimga sovg'a» bo'limlarida ko'rinsin (Otamga, Onamga, ...)", related_name='tagged_products', to='store.promocategory', verbose_name="Kimga sovg'a"),
        ),
    ]
