# Generated by Django 4.2.29 on 2026-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_promo_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Qisqa matn')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Rasm')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Tugma matni')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Tugma havolasi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
