# Generated by Django 4.2.29 on 2026-03-04 17:45

from django.db import migrations, models
import django.db.models.deletion


def copy_product_image_to_productimage(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    ProductImage = apps.get_model('store', 'ProductImage')
    for product in Product.objects.all():
        if hasattr(product, 'image') and product.image:
            ProductImage.objects.create(product=product, image=product.image, order=0)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_banner_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmi',
                'verbose_name_plural': 'Mahsulot rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(copy_product_image_to_productimage, noop),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
