# Generated by Django 4.2.29 on 2026-03-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_images_1_to_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Xususiyat nomi')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Qiymat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='store.product')),
            ],
            options={
                'verbose_name': 'Mahsulot xususiyati',
                'verbose_name_plural': 'Mahsulot xususiyatlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
