# Generated by Django 6.0.3 on 2026-03-04 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_add_product_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': 'Savatcha', 'verbose_name_plural': 'Savatchalar'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Savat elementi', 'verbose_name_plural': 'Savat elementlari'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='promocategory',
            options={'ordering': ['order', 'id'], 'verbose_name': "Kimga sovg'a (promo)", 'verbose_name_plural': "Kimga sovg'a (promo kategoriyalar)"},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Sessiya ID'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.cart', verbose_name='Savatcha'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qoʻshilgan sana'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='store.cart', verbose_name='Savatcha'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma sanasi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Masalan: Surprise box, Gul buketi', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Kategoriya (mahsulot turi)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Qoʻshilgan sana'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Xit savdo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_categories',
            field=models.ManyToManyField(blank=True, help_text="Mahsulot qaysi «Kimga sovg'a» bo'limlarida ko'rinsin: Onamga, Otamga, Sevgilimga va h.k.", related_name='tagged_products', to='store.promocategory', verbose_name="Kim uchun (sovg'a kimga mos)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='store.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promo_categories/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
