# Generated by Django 6.0.3 on 2026-03-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Masalan: 10.00 = 10%', max_digits=5, null=True, verbose_name='Chegirma foizi'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Avtomatik hisoblanadi agar discount_percent berilgan bo'lsa", max_digits=10, null=True, verbose_name='Chegirma narxi'),
        ),
        migrations.AddField(
            model_name='product',
            name='favorite_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sevimlilar soni'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sotilgan soni'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ombordagi miqdor'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ko'rilishlar soni"),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Xit savdo'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='store_product_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='store_product_feat_active_idx'),
        ),
    ]
