# Generated by Django 6.0.3 on 2026-03-04 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_ecommerce_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='analytics', serialize=False, to='store.product', verbose_name='Mahsulot')),
                ('views', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ko'rilishlar")),
                ('favorites', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sevimlilar')),
                ('cart_additions', models.PositiveIntegerField(db_index=True, default=0, verbose_name="Savatga qo'shilgan")),
                ('purchases', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sotilgan (dona)')),
                ('last_viewed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Oxirgi ko'rilgan")),
            ],
            options={
                'verbose_name': 'Mahsulot analitikasi',
                'verbose_name_plural': 'Mahsulotlar analitikasi',
                'indexes': [models.Index(fields=['-views'], name='store_prodan_views_idx'), models.Index(fields=['-purchases'], name='store_prodan_purch_idx'), models.Index(fields=['-last_viewed_at'], name='store_prodan_lastview_idx')],
            },
        ),
    ]
