# Generated by Django 6.0.3 on 2026-03-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='Sessiya ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Qoʻshilgan sana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_entries', to='store.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Sevimlilar',
                'verbose_name_plural': 'Sevimlilar',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('session_id', 'product'), name='unique_wishlist_session_product')],
            },
        ),
    ]
