# Generated by Django 4.2.29 on 2026-03-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Yetkazib berish manzili'),
        ),
    ]
