# Generated by Django 4.2.29 on 2026-03-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_cart_to_foreignkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_note',
            field=models.TextField(blank=True, default='', help_text="Faqat admin panelda ko'rinadi va buyurtma Telegram botga yuborilganda chekda chiqadi. Saytda ko'rinmaydi.", verbose_name='Buyurtma eslatmasi'),
        ),
    ]
