# Generated by Django 4.2.29 on 2026-03-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_banner_products_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(blank=True, max_length=500, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(max_length=500, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='promocategory',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasm URL'),
        ),
    ]
