# Generated by Django 6.0.3 on 2026-03-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, verbose_name='Matn')),
                ('icon', models.CharField(blank=True, help_text='CSS class yoki icon nomi, masalan: truck, gift, headphones', max_length=100, verbose_name='Icon')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xizmat sahifasi',
                'verbose_name_plural': 'Xizmat sahifalari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
