# Generated by Django 4.2.29 on 2026-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicepageimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='content',
            field=models.TextField(blank=True, verbose_name='Matn (HTML mumkin)'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS class yoki icon nomi (ixtiyoriy)', max_length=100, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='image',
            field=models.ImageField(blank=True, help_text="Bosh sahifa va ro'yxatda ko'rinadigan rasm. Bo'sh qoldirilsa galereyadagi birinchi rasm ishlatiladi.", null=True, upload_to='services/', verbose_name='Kartochka rasmi'),
        ),
    ]
